name: canerline_app
description: "app for canerline"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.7
  supabase_flutter: ^2.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - lib/assets/images/logo/introduction.svg
    - lib/assets/images/logo/introduction.png
    - lib/assets/images/logo/LogoText.svg
    - lib/assets/images/logo/HeartLogo.svg
    - lib/assets/icons/Hospital.svg
    - lib/assets/icons/Financial.svg
    - lib/assets/icons/Clinics.svg
    - lib/assets/icons/Blogs.svg
    - lib/assets/icons/Bell.svg
    - lib\assets\images\jpeg\spmc.jpg

  fonts:
    - family: Gilroy
      fonts:
        - asset: lib/assets/fonts/Gilroy-Black.ttf
        - asset: lib/assets/fonts/Gilroy-BlackItalic.ttf
        - asset: lib/assets/fonts/Gilroy-Bold.ttf
        - asset: lib/assets/fonts/Gilroy-BoldItalic.ttf
        - asset: lib/assets/fonts/Gilroy-ExtraBold.ttf
        - asset: lib/assets/fonts/Gilroy-ExtraBoldItalic.ttf
        - asset: lib/assets/fonts/Gilroy-Heavy.ttf
        - asset: lib/assets/fonts/Gilroy-HeavyItalic.ttf
        - asset: lib/assets/fonts/Gilroy-Light.ttf
        - asset: lib/assets/fonts/Gilroy-LightItalic.ttf
        - asset: lib/assets/fonts/Gilroy-Medium.ttf
        - asset: lib/assets/fonts/Gilroy-MediumItalic.ttf
        - asset: lib/assets/fonts/Gilroy-Regular.ttf
        - asset: lib/assets/fonts/Gilroy-RegularItalic.ttf
        - asset: lib/assets/fonts/Gilroy-SemiBold.ttf
        - asset: lib/assets/fonts/Gilroy-SemiBoldItalic.ttf
        - asset: lib/assets/fonts/Gilroy-Thin.ttf
        - asset: lib/assets/fonts/Gilroy-ThinItalic.ttf
        - asset: lib/assets/fonts/Gilroy-UltraLight.ttf
        - asset: lib/assets/fonts/Gilroy-UltraLightItalic.ttf

  uses-material-design: true
