name: cancerline_companion
description: "A companion app for CancerLine"
publish_to: "none"
version: 2.0.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  go_router: ^14.7.2
  supabase_flutter: ^2.8.3
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  lucide_icons: ^0.257.0
  lucide_icons_flutter: ^1.2.6
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  intl: ^0.20.2
  syncfusion_flutter_charts: ^28.2.4
  pdf: ^3.11.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  flutter_pdfview: ^1.4.0
  device_info_plus: ^11.3.0
  url_launcher: ^6.1.7
  buttons_tabbar: ^1.3.15
  readmore: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - lib/assets/images/logo/introduction.svg
    - lib/assets/images/logo/introduction.png
    - lib/assets/images/logo/LogoText.svg
    - lib/assets/images/logo/HeartLogo.svg
    - lib/assets/icons/Supportgroups.svg
    - lib/assets/icons/Hospital.svg
    - lib/assets/icons/Financial.svg
    - lib/assets/icons/Oncologists.svg
    - lib/assets/icons/Blogs.svg
    - lib/assets/icons/Bell.svg
    - lib/assets/images/jpeg/spmc.jpg
    - lib/assets/images/Journal/Angel.png
    - lib/assets/images/Journal/Angry.png
    - lib/assets/images/Journal/Awsome.png
    - lib/assets/images/Journal/Calm.png
    - lib/assets/images/Journal/Disappointed.png
    - lib/assets/images/Journal/Happy.png
    - lib/assets/images/Journal/Inlove.png
    - lib/assets/images/Journal/Sad.png

  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/logo/Icon-Output(Release)/android/play_store_512.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_foreground: "lib/assets/images/logo/Icon-Output(Release)/android/play_store_512.png"
  adaptive_icon_background: "#ffffff"
