name: canerline_app
description: "app for canerline"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - lib/assets/images/logo/introduction.svg
    - lib/assets/images/logo/introduction.png
    - lib/assets/images/logo/LogoText.svg
    - lib/assets/images/logo/HeartLogo.svg
  uses-material-design: true
