name: canerline_app
description: "app for canerline"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.7
  supabase_flutter: ^2.7.0
  google_fonts: ^6.0.0
  google_maps_flutter: ^2.9.0
  lucide_icons: ^0.257.0
  lucide_icons_flutter: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - lib/assets/images/logo/introduction.svg
    - lib/assets/images/logo/introduction.png
    - lib/assets/images/logo/LogoText.svg
    - lib/assets/images/logo/HeartLogo.svg
    - lib/assets/icons/Hospital.svg
    - lib/assets/icons/Financial.svg
    - lib/assets/icons/Oncologists.svg
    - lib/assets/icons/Blogs.svg
    - lib/assets/icons/Bell.svg
    - lib\assets\images\jpeg\spmc.jpg
    - lib/assets/images/Journal/Angel.png
    - lib/assets/images/Journal/Angry.png
    - lib/assets/images/Journal/Awsome.png
    - lib/assets/images/Journal/Calm.png
    - lib/assets/images/Journal/Disappointed.png
    - lib/assets/images/Journal/Happy.png
    - lib/assets/images/Journal/Inlove.png
    - lib/assets/images/Journal/Sad.png

  uses-material-design: true
